# Generated by Django 6.0.2 on 2026-02-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0005_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_text',
            field=models.TextField(blank=True, null=True, verbose_name='Правильный текстовый ответ'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple', 'С выбором ответа'), ('text', 'Письменный ответ')], default='multiple', max_length=20, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.FloatField(verbose_name='Баллы'),
        ),
    ]
