# Generated by Django 6.0.2 on 2026-03-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0006_question_correct_text_question_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time_limit',
            field=models.PositiveIntegerField(default=10, verbose_name='Лимит времени (в минутах)'),
        ),
    ]
