# Generated by Django 6.0.2 on 2026-05-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0008_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
