# Generated by Django 6.0.2 on 2026-05-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0009_test_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество попыток'),
        ),
    ]
