# Generated by Django 6.0.2 on 2026-05-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0011_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
