# Generated by Django 6.0.2 on 2026-05-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0012_alter_test_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Доступен с'),
        ),
        migrations.AddField(
            model_name='test',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Доступен до'),
        ),
    ]
