# Generated by Django 6.0.2 on 2026-06-18 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0016_activitylog_notification_testtemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bank_images/', verbose_name='Изображение')),
                ('question_type', models.CharField(choices=[('multiple', 'С выбором ответа'), ('text', 'Письменный ответ')], default='multiple', max_length=20, verbose_name='Тип')),
                ('correct_text', models.TextField(blank=True, null=True, verbose_name='Правильный текстовый ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_questions', to='tests_app.testcategory', verbose_name='Категория')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_questions', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Вопрос из банка',
                'verbose_name_plural': 'Банк вопросов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBankAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Ответ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests_app.questionbank')),
            ],
        ),
    ]
