# Generated by Django 6.0.2 on 2026-06-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0017_questionbank_questionbankanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbankanswer',
            name='question',
        ),
        migrations.DeleteModel(
            name='QuestionBank',
        ),
        migrations.DeleteModel(
            name='QuestionBankAnswer',
        ),
    ]
